version: "3"
services:
 app:
    build: .
    environment:
      - HOST=${HOST}
      - PORT=${PORT}
      - USER=${USER}
      - PASS=${PASS}
      - NAME=${NAME}
      - API_PORT=${API_PORT}
      - OWNER_UUID=${OWNER_UUID}
      - SECRET=${SECRET}
    ports:
      - "8080:8080"
    depends_on:
      - db
 db:
    image: postgres
    environment:
      - POSTGRES_USER=${USER}
      - POSTGRES_PASSWORD=${PASS}
      - POSTGRES_DB=${NAME}
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
 db-data:
