apiVersion: apps/v1
kind: Deployment
metadata:
 name: go-app
spec:
 replicas: 2
 selector:
    matchLabels:
      app: go-app
 template:
    metadata:
      labels:
        app: go-app
    spec:
      containers:
      - name: go-app
        image: vampireknight/trip:latest
        imagePullPolicy: Always
        env:
        - name: HOST
          valueFrom:
            configMapKeyRef:
              name: go-app-config
              key: HOST
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: go-app-config
              key: PORT
        - name: API_PORT
          valueFrom:
            configMapKeyRef:
              name: go-app-config
              key: API_PORT
        - name: ALLOWED_ORIGIN
          valueFrom:
            configMapKeyRef:
              name: go-app-config
              key: ALLOWED_ORIGIN
        - name: NAME
          valueFrom:
            configMapKeyRef:
              name: go-app-config
              key: NAME
        - name: USER
          valueFrom:
            secretKeyRef:
              name: go-app-secrets
              key: USER
        - name: PASS
          valueFrom:
            secretKeyRef:
              name: go-app-secrets
              key: PASS
        - name: OWNER_UUID
          valueFrom:
            secretKeyRef:
              name: go-app-secrets
              key: OWNER_UUID
        - name: SECRET
          valueFrom:
            secretKeyRef:
              name: go-app-secrets
              key: SECRET
