apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: go-app-secrets
              key: USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: go-app-secrets
              key: PASS
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: go-app-config
              key: NAME
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data # Default PostgreSQL data directory
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: postgres-pvc # Use the PVC defined below
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi # Adjust size as needed      
